/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AISettingsDialog: typeof import('./components/AISettingsDialog.vue')['default']
    BookSwitcher: typeof import('./components/BookSwitcher.vue')['default']
    CategoryDetailDialog: typeof import('./components/CategoryDetailDialog.vue')['default']
    CategoryManagerDialog: typeof import('./components/CategoryManagerDialog.vue')['default']
    CsvImportDialog: typeof import('./components/CsvImportDialog.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    QuarterPicker: typeof import('./components/QuarterPicker.vue')['default']
    TitleBar: typeof import('./components/TitleBar.vue')['default']
    TransactionDialog: typeof import('./components/TransactionDialog.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
